### ISSUE TITLE
NameError: global name 'index' is not defined

### ISSUE THREAD

**Issue by sergeiwallace** [kjchavez/cnn-project#1]
When I try to run the `create_dataset.sh` script, I get the error:

```
Processing SoccerJuggling/v_SoccerJuggling_g11_c02.avi ...
Couldn't open video
...
...
...
File "/home/user/cnn-project/src/preprocessing/convert2lmdb.py", line 27, in read_clip
print "Crashed at index %d." % index
NameError: global name 'index' is not defined
```

Where is this index variable coming from?

**Comment by kjchavez** [comment]
It shouldn't be there. Don't remember where it came from, but it definitely has no business being there. I just updated the master branch to get rid of it. At any rate, this line is only reached if the script is failing to read the video file which is the underlying problem. Can you open the file with your default video player?

**Comment by sergeiwallace** [comment]
Oh, gotcha. Yeah, I was being dumb. I had forgotten to unrar the folder...
